name: SpecFlow Lifecycle Extension
maintainer: mellanon
status: building
created: 2026-01-31
license: MIT
type: bundle
upstream: jcfischer/specflow-bundle
fork: mellanon/specflow-bundle
source_branch: main
contrib_branch: contrib/specflow-lifecycle
paths:
  - src/commands/brownfield.ts
  - src/commands/review.ts
  - src/commands/release.ts
  - src/lib/delta-spec.ts

contributors:
  mellanon:
    zone: maintainer
    since: 2026-01-31
  jcfischer:
    zone: trusted
    since: 2026-01-31
